### ISSUE TITLE
Web page displays->  Waiting for device response...     I'm confused.

### ISSUE THREAD

**Issue by RudyFiero** [alexshavlovsky/ESP8266WebSocketsWebGUI#1]
Home Icon  and then   Waiting for device response...      

I don't know anything about modbus, but I thought your framework looked good so I wanted to try it. I have an LCD and RTC/EEPROM included. The problem is that I can't figure out what to do with it.

I was hoping the WEBGIUApp would require less to get it going than the  WebGUIAppRTU.ino example. Do I need to program a second ESP8266 with WebGUIAppRTU.ino ?

**Comment by alexshavlovsky** [comment]
Hi, sorry for the late response...
It looks like you cannot establish a websocket connection with a board:
1. Make sure that you have installed the ESPAsyncTCP library and have correctly configured the arduinoWebSockets  library. Check this code lines:
`#define WEBSOCKETS_NETWORK_TYPE NETWORK_ESP8266_ASYNC`
`#define WEBSOCKETS_SERVER_CLIENT_MAX (2)`
2. Make sure that your browser correctly establishes a websocket connection.
3. In the Firefox press the "Ctrl+Shift+E" and check the "Network monitor" tab of "Development Tools". Refresh the page. You should see two requests. And the URL of the second request must be "http://192.168.0.5:81/", and the status code must be "101".
4.  In the Firefox press the "Ctrl+Shift+K" and check the "Web console" tab of "Development Tools".
Refresh the page. You should see something like this:
```

To   ESP: M1  192.168.0.5:78:1
From ESP: x  192.168.0.5:84:1
From ESP: <div class="top">
<p>ESP menu</p>
</div>
```


......... and so on..................

5. You need not to program a second ESP8266 with WebGUIAppRTU.ino. WEBGIUApp.ino is the minimum required example.

![network](https://user-images.githubusercontent.com/28875025/29239689-9261174e-7f5c-11e7-8d89-2d032c6c37b7.png)

![console](https://user-images.githubusercontent.com/28875025/29239688-8e5856ee-7f5c-11e7-8ce6-be347b2668db.png)

**Comment by RudyFiero** [comment]
I will check on all this and give it another try.
Thanks.

**Comment by RudyFiero** [comment]
I finally made the changes you said above (and had also wrote in the example) and it works now. I can see the communications from the esp in Firefox and Chrome. Now I need to spend some time to figure out how I can use this. 

Thank you for your help.
